/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApplicationsApplicationIdRouteImport } from './routes/applications.$applicationId'
import { Route as ApplyJobIdRouteImport } from './routes/apply.$jobId'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'
import { Route as CompanyIndexRouteImport } from './routes/company.index'
import { Route as CompanyPostJobRouteImport } from './routes/company.post-job'
import { Route as CompanyProfileRouteImport } from './routes/company.profile'
import { Route as HiringIndexRouteImport } from './routes/hiring.index'
import { Route as HiringJobsJobIdApplicantsRouteImport } from './routes/hiring.jobs.$jobId.applicants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdRoute =
  ApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplyJobIdRoute = ApplyJobIdRouteImport.update({
  id: '/apply/$jobId',
  path: '/apply/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPostJobRoute = CompanyPostJobRouteImport.update({
  id: '/company/post-job',
  path: '/company/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyProfileRoute = CompanyProfileRouteImport.update({
  id: '/company/profile',
  path: '/company/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringIndexRoute = HiringIndexRouteImport.update({
  id: '/hiring/',
  path: '/hiring/',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringJobsJobIdApplicantsRoute =
  HiringJobsJobIdApplicantsRouteImport.update({
    id: '/hiring/jobs/$jobId/applicants',
    path: '/hiring/jobs/$jobId/applicants',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/company/post-job': typeof CompanyPostJobRoute
  '/company/profile': typeof CompanyProfileRoute
  '/companies/': typeof CompaniesIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/hiring/': typeof HiringIndexRoute
  '/hiring/jobs/$jobId/applicants': typeof HiringJobsJobIdApplicantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/company/post-job': typeof CompanyPostJobRoute
  '/company/profile': typeof CompanyProfileRoute
  '/companies': typeof CompaniesIndexRoute
  '/company': typeof CompanyIndexRoute
  '/hiring': typeof HiringIndexRoute
  '/hiring/jobs/$jobId/applicants': typeof HiringJobsJobIdApplicantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/company/post-job': typeof CompanyPostJobRoute
  '/company/profile': typeof CompanyProfileRoute
  '/companies/': typeof CompaniesIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/hiring/': typeof HiringIndexRoute
  '/hiring/jobs/$jobId/applicants': typeof HiringJobsJobIdApplicantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/jobs'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/applications/$applicationId'
    | '/apply/$jobId'
    | '/companies/$slug'
    | '/company/post-job'
    | '/company/profile'
    | '/companies/'
    | '/company/'
    | '/hiring/'
    | '/hiring/jobs/$jobId/applicants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/jobs'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/applications/$applicationId'
    | '/apply/$jobId'
    | '/companies/$slug'
    | '/company/post-job'
    | '/company/profile'
    | '/companies'
    | '/company'
    | '/hiring'
    | '/hiring/jobs/$jobId/applicants'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/jobs'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/applications/$applicationId'
    | '/apply/$jobId'
    | '/companies/$slug'
    | '/company/post-job'
    | '/company/profile'
    | '/companies/'
    | '/company/'
    | '/hiring/'
    | '/hiring/jobs/$jobId/applicants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApplicationsApplicationIdRoute: typeof ApplicationsApplicationIdRoute
  ApplyJobIdRoute: typeof ApplyJobIdRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  CompanyPostJobRoute: typeof CompanyPostJobRoute
  CompanyProfileRoute: typeof CompanyProfileRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
  HiringIndexRoute: typeof HiringIndexRoute
  HiringJobsJobIdApplicantsRoute: typeof HiringJobsJobIdApplicantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId': {
      id: '/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof ApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$jobId': {
      id: '/apply/$jobId'
      path: '/apply/$jobId'
      fullPath: '/apply/$jobId'
      preLoaderRoute: typeof ApplyJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/post-job': {
      id: '/company/post-job'
      path: '/company/post-job'
      fullPath: '/company/post-job'
      preLoaderRoute: typeof CompanyPostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/profile': {
      id: '/company/profile'
      path: '/company/profile'
      fullPath: '/company/profile'
      preLoaderRoute: typeof CompanyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/': {
      id: '/hiring/'
      path: '/hiring'
      fullPath: '/hiring/'
      preLoaderRoute: typeof HiringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/jobs/$jobId/applicants': {
      id: '/hiring/jobs/$jobId/applicants'
      path: '/hiring/jobs/$jobId/applicants'
      fullPath: '/hiring/jobs/$jobId/applicants'
      preLoaderRoute: typeof HiringJobsJobIdApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApplicationsApplicationIdRoute: ApplicationsApplicationIdRoute,
  ApplyJobIdRoute: ApplyJobIdRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  CompanyPostJobRoute: CompanyPostJobRoute,
  CompanyProfileRoute: CompanyProfileRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  CompanyIndexRoute: CompanyIndexRoute,
  HiringIndexRoute: HiringIndexRoute,
  HiringJobsJobIdApplicantsRoute: HiringJobsJobIdApplicantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
